Trace file /u01/app/oracle/diag/rdbms/orcl19/orcl19/trace/orcl19_fenc_16330.trc
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0
Build label:    RDBMS_19.3.0.0.0DBRU_LINUX.X64_190417
ORACLE_HOME:    /u01/app/oracle/product/19c/dbhome_1
System name:	Linux
Node name:	cust-db19
Release:	5.4.17-2036.102.0.2.el7uek.x86_64
Version:	#2 SMP Tue Jan 5 12:41:34 PST 2021
Machine:	x86_64
Instance name: orcl19
Redo thread mounted by this instance: 0 <none>
Oracle process number: 31
Unix process pid: 16330, image: oracle@cust-db19 (FENC)


*** 2021-03-07T18:14:23.546474+00:00 (CDB$ROOT(1))
*** SESSION ID:(254.41360) 2021-03-07T18:14:23.546508+00:00
*** CLIENT ID:() 2021-03-07T18:14:23.546514+00:00
*** SERVICE NAME:() 2021-03-07T18:14:23.546519+00:00
*** MODULE NAME:() 2021-03-07T18:14:23.546524+00:00
*** ACTION NAME:() 2021-03-07T18:14:23.546528+00:00
*** CLIENT DRIVER:() 2021-03-07T18:14:23.546533+00:00
*** CONTAINER ID:(1) 2021-03-07T18:14:23.546538+00:00
 
2021-03-07 18:14:23.546 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x189a1b00 [0000000000000014] { gipcAddress : name 'ipc://scls_opct_cust-db19', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
2021-03-07 18:14:23.546 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x189a1b00 [000000000000001c] { gipcAddress : name 'ipc://scls_opct_cust-db19', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
[ default][ default]u_set_comp_error: comptype '103' : error '29'
2021-03-07 18:14:23.548 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x189a2a20 [000000000000002d] { gipcAddress : name 'clsc://(ADDRESS=(PROTOCOL=ipc)(KEY=OHASD_UI_SOCKET)(GIPCID=00000000-00000000-0))', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
2021-03-07 18:14:23.548 : [GIPCXCPT][GIPCXCPT] gipcConnectSyncF [clscrsconGipcConnect : clscrscon.c : 686]: EXCEPTION[ ret gipcretConnectionRefused (29) ]  failed sync connect endp 0x189ab2e0 [000000000000002a] { gipcEndpoint : localAddr 'clsc://(ADDRESS=(PROTOCOL=ipc)(KEY=)(GIPCID=00000000-00000000-0))', remoteAddr 'clsc://(ADDRESS=(PROTOCOL=ipc)(KEY=OHASD_UI_SOCKET)(GIPCID=00000000-00000000-0))', numPend 0, numReady 0, numDone 0, numDead 0, numTransfer 0, objFlags 0x0, pidPeer 0, readyRef (nil), ready 0, wobj 0x189a1a30, sendp 0x189a0a70 status 13flags 0xa108071a, flags-2 0x0, usrFlags 0x0 }, addr 0x189a2a20 [000000000000002d] { gipcAddress : name 'clsc://(ADDRESS=(PROTOCOL=ipc)(KEY=OHASD_UI_SOCKET)(GIPCID=00000000-00000000-0))', objFlags 0x0, addrFlags 0x4 }, flags 0x0
2021-03-07 18:14:23.548 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x189a0e00 [0000000000000032] { gipcAddress : name 'ipc://scls_opct_cust-db19', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
2021-03-07 18:14:23.549 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x189a0f70 [000000000000003a] { gipcAddress : name 'ipc://scls_opct_cust-db19', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
[ default][ default]u_set_comp_error: comptype '103' : error '29'
2021-03-07 18:14:23.550 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x189aadc0 [000000000000004a] { gipcAddress : name 'ipc://scls_opct_cust-db19', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
2021-03-07 18:14:23.550 : [GIPCXCPT][GIPCXCPT] gipcInternalConnectSync: failed sync request, addr 0x189aaf80 [0000000000000052] { gipcAddress : name 'ipc://scls_opct_cust-db19', objFlags 0x0, addrFlags 0x4 }, ret gipcretConnectionRefused (29)
2021-03-07 18:14:23.551 : [  OCRRAW][  OCRRAW]proprioo: cannot get current configuration (33)
[ default][ default]u_set_gbl_comp_error: comptype '107' : error '2'
2021-03-07 18:14:23.551 : [  OCRRAW][  OCRRAW]proprinit: Could not open raw device 
2021-03-07 18:14:23.551 : [ default][ default]a_init:7!: Backend init unsuccessful : [33]
2021-03-07 18:14:23.551 : [ default][ default]clsutcnr:5.1: procr_init_ext failed [33] with bootlevel [131072]. Error data []. Return [5]
